### ISSUE TITLE
Error:'res.users' object has no attribute 'plan_id'

### ISSUE THREAD

**Issue by jorsea** [yelizariev/odoo-saas-tools#9]
By step after configuration is complete, when I open odoo.Locat/page/start and enter any letters, click Try now, prompted the following error.

Error:'res.users' object has no attribute 'plan_id'

**Comment by jorsea** [comment]
![planid](https://cloud.githubusercontent.com/assets/9857984/9129729/08b109d8-3d0e-11e5-8ae1-49e6c79ffa22.jpg)

**Comment by shingonoide** [comment]
:+1: I can confirm this error.

**Comment by yelizariev** [comment]
Hi, thank you reporting.

We have made a lot refactoring on saas_portal and have not updated modules below:
* saas_portal_start
* saas_portal_signup 

Currently we work on base modules and modules for demo databases. 

Contact me, if you are ready to contribute to fix this  issue.

**Comment by jorsea** [comment]
![image](https://cloud.githubusercontent.com/assets/9857984/9158294/d132dd0c-3f46-11e5-9c1a-5499a83378b0.png)
update saas_portal error

**Comment by jorsea** [comment]
![image](https://cloud.githubusercontent.com/assets/9857984/9158327/6215340a-3f47-11e5-90d2-5880bb5269cb.png)

**Comment by jorsea** [comment]
![image](https://cloud.githubusercontent.com/assets/9857984/9158348/bd46e436-3f47-11e5-80f9-b280bfad6720.png)

**Comment by jorsea** [comment]
Hi,yelizariev
Could you give me  the two modules that has updated below：

saas_portal_start
saas_portal_signup

And this is my email：qmy@luyuantong.com  

thanks

**Comment by jorsea** [comment]
Contact me，thanks.

**Comment by jorsea** [comment]
Waiting for you update!

**Comment by yelizariev** [comment]
@jorsea 
could you prepare Pull Request?

**Comment by jorsea** [comment]
ok

**Comment by infoelliex** [comment]
The error I saw is 500: Internal Server Error - "Warning: There is no plan configured" .... ?

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/website/models/ir_http.py", line 199, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 145, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 666, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_http.py", line 171, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo-server/openerp/http.py", line 684, in dispatch
    r = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/custom/addons/saas_portal/controllers/main.py", line 27, in add_new_client
    plan = self.get_plan(post.get('plan_id'))
  File "/opt/odoo/custom/addons/saas_portal/controllers/main.py", line 48, in get_plan
    raise exceptions.Warning(_('There is no plan configured'))
Warning: There is no plan configured

**Comment by yelizariev** [comment]
it's too old issue and a lot of update were made. Open new issue is if problem still exist
